export const ENABLE_APPS_SCRIPT_TRANSITION = process.env.NEXT_PUBLIC_ENABLE_APPS_SCRIPT_TRANSITION === "true";
export const ENABLE_BUFFERED_APPS_SCRIPT_SYNC = process.env.NEXT_PUBLIC_ENABLE_BUFFERED_APPS_SCRIPT_SYNC === "true";
export const ENABLE_LEGACY_PREVIEW = process.env.NEXT_PUBLIC_ENABLE_LEGACY_PREVIEW === "true";
export const ENABLE_PREVIEW_LOGIN = process.env.NEXT_PUBLIC_ENABLE_PREVIEW_LOGIN === "true";
